# Dependencies
markdown:         redcarpet
pygments:         true
gems:
  - jekyll-sitemap
# Permalinks
permalink:        pretty

# Setup
title:            ShellDone
tagline:          'Tech & Life'
description:      '<a href="https://twitter.com/gaoxudong" target="_blank">@gaoxudong</a><p>Blogger of ShellDone.Com</p>'
url:              http://shelldone.com
domain:            ShellDone.Com
author:
  name:           'gaoxudong'
  url:            https://twitter.com/gaoxudong

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/shelldonegao/blog