# Dependencies
markdown:         redcarpet
pygments:         true
gems:
  - jekyll-sitemap
# Permalinks
permalink:        pretty

# Setup
title:            五五09
tagline:          'Blog'
description:      '<a href="http://www.weibo.com/u/2023265090" target="_blank">@五五09</a><p>Blogger of snso.cc</p>'
url:              http://snsogbl.github.io/snso/
domain:           http://snsogbl.github.io/snso/
author:
  name:           'yangjie'
  url:            http://www.weibo.com/u/2023265090

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/shelldonegao/blog

baseurl:		  