# Dependencies
markdown:         redcarpet
pygments:         true
gems:
  - jekyll-sitemap
# Permalinks
permalink:        pretty

# Setup
title:            五五09
tagline:          'Tech & Life'
description:      '<a href="https://twitter.com/gaoxudong" target="_blank">@gaoxudong</a><p>Blogger of ShellDone.Com</p>'
url:              http://snsogbl.github.io/snso
domain:           http://snsogbl.github.io/snso
author:
  name:           'yangjie'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

#github:
#  repo:           https://github.com/shelldonegao/blog

baseurl:		  /snso